/**
 * Global setup for the Vitest test suite.
 *
 * Tests must NEVER touch the dev database (the one the app reads from).
 * Without isolation, beforeEach `db.delete(...)` calls in our DB tests
 * wipe rows the user typed into the admin UI.
 *
 * This setup:
 *   1. Reads the *master* DB URL (defaults to the dev one).
 *   2. Carves a sibling database called `enlace_test` on the same Postgres
 *      instance, creating it if missing.
 *   3. Applies every SQL file under `./drizzle/` to that sibling DB
 *      (idempotently — uses CREATE … IF NOT EXISTS / ON CONFLICT semantics
 *      where Drizzle generated them; otherwise tolerates "already exists").
 *
 * The test DB URL is then exposed via `vitest.config.ts → test.env.DATABASE_URL`
 * so every test worker connects to `enlace_test` instead of the dev DB.
 */
import postgres from "postgres";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const TEST_DB_NAME = "enlace_test";

function deriveTestUrl(masterUrl: string): string {
  const idx = masterUrl.lastIndexOf("/");
  if (idx === -1) throw new Error(`Cannot parse DATABASE_URL: ${masterUrl}`);
  // Strip the trailing "/dbname[?query]" segment.
  const noDb = masterUrl.slice(0, idx);
  return `${noDb}/${TEST_DB_NAME}`;
}

export async function setup(): Promise<void> {
  const masterUrl =
    process.env.MASTER_DATABASE_URL ??
    process.env.DATABASE_URL ??
    "postgres://enlace:enlace@database:5432/enlace";
  const testUrl = deriveTestUrl(masterUrl);

  // 1) Create the test DB if missing. CREATE DATABASE can't run in a
  // transaction, so use a one-shot connection on the master URL.
  const master = postgres(masterUrl, { max: 1, prepare: false, onnotice: () => {} });
  try {
    const existing = await master.unsafe(
      `SELECT 1 FROM pg_database WHERE datname = '${TEST_DB_NAME}'`,
    );
    if (existing.length === 0) {
      await master.unsafe(`CREATE DATABASE "${TEST_DB_NAME}"`);
    }
  } finally {
    await master.end({ timeout: 1 });
  }

  // 2) Apply every drizzle/*.sql migration to the test DB. These files are
  // generated by drizzle-kit and contain a `--> statement-breakpoint`
  // delimiter between statements.
  const migrationsDir = join(process.cwd(), "drizzle");
  const sqlFiles = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const test = postgres(testUrl, { max: 1, prepare: false, onnotice: () => {} });
  try {
    for (const file of sqlFiles) {
      const raw = readFileSync(join(migrationsDir, file), "utf8");
      const statements = raw
        .split("--> statement-breakpoint")
        .map((s) => s.trim())
        .filter(Boolean);
      for (const stmt of statements) {
        try {
          await test.unsafe(stmt);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          // Tolerate "already exists" / "duplicate" — migrations are
          // applied idempotently across runs.
          if (!/already exists|duplicate/i.test(message)) {
            throw new Error(`Failed in ${file}: ${message}\n--- STMT ---\n${stmt}`);
          }
        }
      }
    }
  } finally {
    await test.end({ timeout: 1 });
  }
}

export async function teardown(): Promise<void> {
  // Keep the test DB around between runs so re-runs are fast. Tests
  // beforeEach hooks already truncate rows scoped to the test DB.
}
